Info
Family-Suarez/Porfolio-Samy pull request #2
Opened 2022-02-12 03:51 UTC by SamuelSuarezDev

### **Comentarios resueltos y parte de Info terminada**
Ademas de arreglar los problemas del header, se hizo tambíen la parte del info
### INFO Desktop
![image](https://user-images.githubusercontent.com/74521899/153695558-80a3d08a-c7ee-4204-891f-25f1a4322712.png)
### INFO Mobile 
![image](https://user-images.githubusercontent.com/74521899/153695580-2368b032-18fe-444b-adb7-ca1a6dd09826.png)

2022-02-12 20:12 UTC, DanielSuarezDev requested changes
Siento que aún le falta mucho orden , poner madures en el código, falta indexar el code (integre un linter con prettier) y adicional a eso no veo buenas prácticas en:
1. HTML semántico
2. Nombres de variables

2022-02-12 20:12 UTC, DanielSuarezDev commented on Css/desktop.css
> +  --background-color: #081638;
Si yo quiero llamar background color que color sería ?

2022-02-12 20:12 UTC, DanielSuarezDev commented on Css/mobile.css
> +  background-image: url("../Assets/image\ 1\ \(2\).png");
Otra ves nombres de archivos con espacios ?

2022-02-12 20:12 UTC, DanielSuarezDev commented on index.html
> +    <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
Porque tantos br ? Eso no es buena práctica

2022-02-13 22:52 UTC, SamuelSuarezDev commented on index.html
> +    <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
A no es solo para que halla espacio ya los quito

2022-02-13 22:54 UTC, merged